export const DRAW_CONSTANTS = {
  MIN_NUMBER: 1,
  MAX_NUMBER: 45,
  NUMBERS_COUNT: 5,
  MIN_STABLEFORD_SCORE: 1,
  MAX_STABLEFORD_SCORE: 45,
  MAX_STORED_SCORES: 5,
  MIN_CHARITY_PERCENT: 10,
  DEFAULT_PRIZE_POOL_PERCENT: 50,
  TIER_5_SHARE: 0.40, // 40%
  TIER_4_SHARE: 0.35, // 35%
  TIER_3_SHARE: 0.25, // 25%
};
