export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LAPSED: 'LAPSED',
  CANCELLED: 'CANCELLED',
};

export const DRAW_STATUS = {
  DRAFT: 'DRAFT',
  SIMULATED: 'SIMULATED',
  PUBLISHED: 'PUBLISHED',
  COMPLETED: 'COMPLETED',
};

export const WINNER_STATUS = {
  PENDING_PROOF: 'PENDING_PROOF',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
};
